/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.tomitribe.crest;

import org.tomitribe.crest.api.Loader;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.URL;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.Iterator;
import java.util.List;

import static java.util.Arrays.asList;

/**
 * Loader implementation that reads class names from {@code crest-commands.txt}
 * generated by the crest-maven-plugin's {@code descriptor} goal at build time.
 *
 * <p>When the descriptor goal is used, it registers this class via
 * {@code META-INF/services/org.tomitribe.crest.api.Loader} so that
 * command discovery happens through the standard Loader mechanism
 * with no runtime classpath scanning required.</p>
 *
 * <p>The returned classes may include {@code @Command}, {@code @Editor},
 * {@code @CrestInterceptor}, and {@code @GlobalOptions} classes.
 * {@link Main#processClass} handles each type appropriately.</p>
 */
public class CrestCommandsLoader implements Loader {

    @Override
    public Iterator<Class<?>> iterator() {
        final ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
        final List<Class<?>> classes = new ArrayList<>();

        loadFromResource(classLoader, "crest-commands.txt", classes);

        return classes.iterator();
    }

    private void loadFromResource(final ClassLoader classLoader, final String resource, final List<Class<?>> classes) {
        for (final String prefix : asList("", "/")) {
            try {
                final Enumeration<URL> urls = classLoader.getResources(prefix + resource);
                final boolean done = urls.hasMoreElements();
                while (urls.hasMoreElements()) {
                    final URL url = urls.nextElement();
                    try (InputStream stream = url.openStream();
                         BufferedReader reader = new BufferedReader(new InputStreamReader(stream))) {
                        String line;
                        while ((line = reader.readLine()) != null) {
                            line = normalize(line);
                            if (line.isEmpty()) {
                                continue;
                            }
                            try {
                                classes.add(classLoader.loadClass(line));
                            } catch (final ClassNotFoundException e) {
                                // skip classes that can't be loaded
                            }
                        }
                    } catch (final IOException ioe) {
                        // no-op
                    }
                }
                if (done) {
                    break;
                }
            } catch (final IOException e) {
                // no-op
            }
        }
    }

    private static String normalize(String line) {
        line = line.trim();
        if (line.startsWith("class ")) {
            line = line.substring(5).trim();
        }
        return line;
    }
}
